name: Build benchmark images

on:
  pull_request:
    branches:
      - main

jobs:
  find-targets:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v3
      - id: find-targets
        run: |
          projects=$(git diff --name-only origin/${{ github.base_ref }} origin/${{ github.head_ref }} | grep OCaml | cut -d '/' -f 1-2 | sort | uniq) | tr '\n' ',' | sed 's/,*$//'
          echo "target=[$projects]"

    outputs:
      targets: ${{ steps.find-targets.outputs.targets }}
      

  build-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    needs:
      - find-targets

    strategy:
      matrix:
        target: ${{ fromJSON(needs.find-targets.outputs.targets) }}

    steps:
      - uses: actions/checkout@v3
